[package]
name = "twocb"
version = "0.1.0"
authors = ["coral <jonas@jonasbengtson.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evmap = "10.0.2"
notify = "4.0.15"
pickledb = "0.4.1"
rusty_v8 = "0.15.0"
serde = {version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
vecmath = "1.0.0"
